[supabase]
url = "https://rlpgvvesqoxvbmtkzuya.supabase.co"
key = "sb_publishable_KFewMQ3g0o6jsPcv4ypu-Q__VUoGbsH"
db_url = "postgresql://postgres:[Qi8M+Y2Nj-hKTT$]@db.rlpgvvesqoxvbmtkzuya.supabase.co:5432/postgres"
